//! scriptc transport generation.
//!
//! [scriptc](https://scriptc.dev) compiles TypeScript into a self-contained
//! native executable and links native code through a manifest-declared C ABI
//! surface. That surface is narrower than the shared eqts C ABI: it has no
//! 64-bit integer class, no pointer parameters, no owned pointer returns, and no
//! runtime symbol lookup. This module therefore emits three artifacts beside the
//! crate's static library:
//!
//! - `eqts_shim.c` adapts the status-and-out-pointer ABI to the classes scriptc
//!   can express, delivering results through call-scoped callbacks and carrying
//!   `u64` handles as a high/low `u32` pair.
//! - `ffi.json` binds the bridge and the crate's static library at link time.
//! - `index.ts` exposes the same camelCase API as the other transports with no
//!   runtime library loading.
//!
//! The generated `index.ts` is scriptc-only. Its `declare function`
//! declarations emit no JavaScript, so the module cannot run under Node, Bun,
//! or Deno.

use std::fmt::Write as _;

use anyhow::{Result, bail};
use serde_json::{Value, json};

use crate::{
    ExportKind, Function, FunctionAbi, OwnedType, Scalar, Type, c_type, scalar_type,
    scriptc_wire_decode, scriptc_wire_encode, ts_type, typescript_name,
};

/// Rust export names that would collide with the shared reactive bridge
/// functions the shim always emits.
const RESERVED_NAMES: [&str; 3] = ["bridge_poll", "bridge_cancel", "bridge_dispose"];

/// The README written beside the generated artifacts.
pub(crate) const README: &str = "# scriptc transport\n\n\
Generated by `cargo eqts build --target scriptc`.\n\n\
- `index.ts` is the TypeScript API. It performs no runtime library loading:\n\
  scriptc binds the `declare function` symbols at the top of the file through\n\
  `ffi.json` at link time.\n\
- `ffi.json` is the scriptc FFI manifest. Pass it to scriptc with `--ffi`.\n\
- `eqts_shim.c` and `eqts_shim.o` bridge scriptc's FFI classes to eqts's shared\n\
  C ABI.\n\
- `lib<name>.a` is this crate built as a static library.\n\n\
Build one self-contained executable with no JavaScript engine and no runtime\n\
library loading:\n\n\
```sh\n\
scriptc build app.ts --ffi ffi.json -o app\n\
```\n\n\
`app.ts` imports `./index.ts`. `index.ts` is scriptc-only, because `declare\n\
function` emits no JavaScript and cannot run under Node, Bun, or Deno. Use\n\
`--target node-napi`, `--target bun`, `--target deno`, `--target node-koffi`, or\n\
`--target wasm` for those runtimes.\n";

/// The scalar classes scriptc's FFI can carry. `u16`, `u64`, `i8`, `i16`, `i64`,
/// and `f32` have no equivalent class.
fn supported_scalar(scalar: Scalar) -> bool {
    matches!(
        scalar,
        Scalar::Void | Scalar::Bool | Scalar::U8 | Scalar::U32 | Scalar::I32 | Scalar::F64
    )
}

fn scalar_name(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::Void => "void",
        Scalar::Bool => "bool",
        Scalar::U8 => "u8",
        Scalar::U16 => "u16",
        Scalar::U32 => "u32",
        Scalar::U64 => "u64",
        Scalar::I8 => "i8",
        Scalar::I16 => "i16",
        Scalar::I32 => "i32",
        Scalar::I64 => "i64",
        Scalar::F32 => "f32",
        Scalar::F64 => "f64",
    }
}

/// The scriptc manifest class for a scalar.
fn abi_class(scalar: Scalar) -> &'static str {
    match scalar {
        Scalar::Bool => "bool",
        Scalar::U8 => "u8",
        Scalar::U32 => "u32",
        Scalar::I32 => "i32",
        Scalar::F64 => "f64",
        _ => unreachable!("unsupported scalar reached scriptc code generation"),
    }
}

/// The generated TypeScript declaration name for one export.
fn bridge_name(function: &Function) -> String {
    let mut name = typescript_name(&function.name);
    if let Some(first) = name.chars().next() {
        name.replace_range(..first.len_utf8(), &first.to_uppercase().to_string());
    }
    format!("eqtsSc{name}")
}

/// The generated C symbol for one export.
fn bridge_symbol(function: &Function) -> String {
    format!("eqts_sc_{}", function.name)
}

/// Reject exports the scriptc target cannot express, before any work is done.
pub(crate) fn validate(functions: &[Function]) -> Result<()> {
    for function in functions {
        if RESERVED_NAMES.contains(&function.name.as_str()) {
            bail!(
                "export `{}` collides with a reserved scriptc bridge name; rename it to build this target",
                function.name
            );
        }
        match &function.kind {
            ExportKind::Function => {
                if function.abi == FunctionAbi::Scalar {
                    for parameter in &function.parameters {
                        require_scalar(function, &parameter.ty, "parameter")?;
                    }
                    require_scalar(function, &function.result, "result")?;
                }
            }
            ExportKind::Stream { item } | ExportKind::Iterator { item } => {
                require_plain(function, item, "item")?;
            }
            ExportKind::Async { .. } => bail!(
                "export `{}` is asynchronous; the scriptc target supports synchronous functions, streams, and iterators only",
                function.name
            ),
            ExportKind::Callback { .. } => bail!(
                "export `{}` is a callback export; the scriptc target supports synchronous functions, streams, and iterators only",
                function.name
            ),
            ExportKind::Object { .. } | ExportKind::Trait { .. } => bail!(
                "export `{}` is a stateful proxy; the scriptc target supports synchronous functions, streams, and iterators only",
                function.name
            ),
        }
    }
    Ok(())
}

fn require_scalar(function: &Function, ty: &Type, role: &str) -> Result<()> {
    let scalar = scalar_type(ty);
    if supported_scalar(scalar) {
        return Ok(());
    }
    bail!(
        "export `{}` has a {role} of type {}, which the scriptc FFI cannot carry; scriptc accepts void, bool, u8, u32, i32, and f64 only",
        function.name,
        scalar_name(scalar)
    )
}

fn require_plain(function: &Function, ty: &Type, role: &str) -> Result<()> {
    if matches!(ty, Type::Owned(OwnedType::Result { .. })) {
        bail!(
            "export `{}` has a {role} of type Result, which has no single TypeScript shape; return the ok type and let a Rust error become an EqtsError",
            function.name
        );
    }
    Ok(())
}

/// Render the C bridge that adapts eqts's shared ABI to scriptc's classes.
pub(crate) fn render_shim(functions: &[Function]) -> String {
    let mut output = String::from(
        "/* Generated by cargo-eqts for the scriptc transport. Do not edit. */\n\
         #include <stddef.h>\n\
         #include <stdint.h>\n\n\
         typedef struct {\n\
         \x20 uint8_t *ptr;\n\
         \x20 size_t len;\n\
         \x20 size_t capacity;\n\
         } EqtsOwnedBuffer;\n\n\
         extern void eqts_buffer_free_v1(uint8_t *ptr, size_t len, size_t capacity);\n\
         extern int32_t eqts_handle_dispose_v1(uint64_t handle);\n\
         extern int32_t eqts_reactive_cancel_v1(uint64_t handle);\n\
         extern int32_t eqts_reactive_poll_v1(uint64_t handle, EqtsOwnedBuffer *output);\n\n",
    );
    for function in functions {
        writeln!(output, "{}", extern_declaration(function))
            .expect("writing to a string cannot fail");
    }
    output.push_str(
        "\nint32_t eqts_sc_bridge_poll(uint32_t hi, uint32_t lo, void (*emit)(const uint8_t *, size_t)) {\n\
         \x20 EqtsOwnedBuffer output = {NULL, 0, 0};\n\
         \x20 int32_t status = eqts_reactive_poll_v1(((uint64_t)hi << 32) | (uint64_t)lo, &output);\n\
         \x20 if (output.ptr != NULL) {\n\
         \x20   if (emit != NULL) emit(output.ptr, output.len);\n\
         \x20   eqts_buffer_free_v1(output.ptr, output.len, output.capacity);\n\
         \x20 }\n\
         \x20 return status;\n\
         }\n\n\
         int32_t eqts_sc_bridge_cancel(uint32_t hi, uint32_t lo) {\n\
         \x20 return eqts_reactive_cancel_v1(((uint64_t)hi << 32) | (uint64_t)lo);\n\
         }\n\n\
         int32_t eqts_sc_bridge_dispose(uint32_t hi, uint32_t lo) {\n\
         \x20 return eqts_handle_dispose_v1(((uint64_t)hi << 32) | (uint64_t)lo);\n\
         }\n\n",
    );
    for function in functions {
        writeln!(output, "{}", bridge_function(function)).expect("writing to a string cannot fail");
    }
    output
}

fn extern_declaration(function: &Function) -> String {
    match &function.kind {
        ExportKind::Function if function.abi == FunctionAbi::Scalar => {
            let mut parameters = function
                .parameters
                .iter()
                .map(|parameter| {
                    format!("{} {}", c_type(scalar_type(&parameter.ty)), parameter.name)
                })
                .collect::<Vec<_>>();
            if !matches!(function.result, Type::Scalar(Scalar::Void)) {
                parameters.push(format!("{} *output", c_type(scalar_type(&function.result))));
            }
            format!(
                "extern int32_t {}({});",
                function.symbol,
                parameters.join(", ")
            )
        }
        ExportKind::Function => format!(
            "extern int32_t {}(const uint8_t *input, size_t len, EqtsOwnedBuffer *output);",
            function.symbol
        ),
        ExportKind::Stream { .. } | ExportKind::Iterator { .. } => format!(
            "extern int32_t {}(const uint8_t *input, size_t len, uint64_t *output);",
            function.symbol
        ),
        ExportKind::Async { .. }
        | ExportKind::Callback { .. }
        | ExportKind::Object { .. }
        | ExportKind::Trait { .. } => unreachable!("unsupported export reached the scriptc shim"),
    }
}

fn bridge_function(function: &Function) -> String {
    let symbol = bridge_symbol(function);
    match &function.kind {
        ExportKind::Function if function.abi == FunctionAbi::Scalar => {
            let parameters = function
                .parameters
                .iter()
                .map(|parameter| {
                    format!("{} {}", c_type(scalar_type(&parameter.ty)), parameter.name)
                })
                .collect::<Vec<_>>();
            let arguments = function
                .parameters
                .iter()
                .map(|parameter| parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let separator = if arguments.is_empty() { "" } else { ", " };
            if matches!(function.result, Type::Scalar(Scalar::Void)) {
                let signature = if parameters.is_empty() {
                    "void".to_owned()
                } else {
                    parameters.join(", ")
                };
                return format!(
                    "int32_t {symbol}({signature}) {{\n  return {}({arguments});\n}}\n",
                    function.symbol
                );
            }
            let result = c_type(scalar_type(&function.result));
            let mut signature = parameters;
            signature.push(format!("void (*emit)({result})"));
            format!(
                "int32_t {symbol}({}) {{\n  {result} output = 0;\n  int32_t status = {}({arguments}{separator}&output);\n  if (status == 0 && emit != NULL) emit(output);\n  return status;\n}}\n",
                signature.join(", "),
                function.symbol
            )
        }
        ExportKind::Function => format!(
            "int32_t {symbol}(const uint8_t *input, size_t len, void (*emit)(const uint8_t *, size_t)) {{\n  EqtsOwnedBuffer output = {{NULL, 0, 0}};\n  int32_t status = {}(input, len, &output);\n  if (output.ptr != NULL) {{\n    if (emit != NULL) emit(output.ptr, output.len);\n    eqts_buffer_free_v1(output.ptr, output.len, output.capacity);\n  }}\n  return status;\n}}\n",
            function.symbol
        ),
        ExportKind::Stream { .. } | ExportKind::Iterator { .. } => format!(
            "int32_t {symbol}(const uint8_t *input, size_t len, void (*emit)(uint32_t, uint32_t)) {{\n  uint64_t handle = 0;\n  int32_t status = {}(input, len, &handle);\n  if (status == 0 && emit != NULL) emit((uint32_t)(handle >> 32), (uint32_t)(handle & 0xffffffffu));\n  return status;\n}}\n",
            function.symbol
        ),
        ExportKind::Async { .. }
        | ExportKind::Callback { .. }
        | ExportKind::Object { .. }
        | ExportKind::Trait { .. } => unreachable!("unsupported export reached the scriptc shim"),
    }
}

/// Render the scriptc FFI manifest that links the bridge and the crate archive.
pub(crate) fn render_manifest(functions: &[Function], archive: &str, shim: &str) -> String {
    let mut entries = functions.iter().map(manifest_entry).collect::<Vec<_>>();
    entries.push(json!({
        "name": "eqtsScBridgePoll",
        "symbol": "eqts_sc_bridge_poll",
        "params": ["u32", "u32", callback_entry(&["bytes"])],
        "returns": "i32",
    }));
    entries.push(json!({
        "name": "eqtsScBridgeCancel",
        "symbol": "eqts_sc_bridge_cancel",
        "params": ["u32", "u32"],
        "returns": "i32",
    }));
    entries.push(json!({
        "name": "eqtsScBridgeDispose",
        "symbol": "eqts_sc_bridge_dispose",
        "params": ["u32", "u32"],
        "returns": "i32",
    }));
    let document = json!({
        "ffi_format": 3,
        "functions": entries,
        "libraries": [format!("./{shim}"), format!("./{archive}")],
        "system_libraries": system_libraries(),
    });
    let mut text =
        serde_json::to_string_pretty(&document).expect("manifest serialization cannot fail");
    text.push('\n');
    text
}

fn callback_entry(classes: &[&str]) -> Value {
    json!({
        "callback": {
            "id": "emit",
            "params": classes,
            "returns": "void",
            "lifetime": "call",
        }
    })
}

fn manifest_entry(function: &Function) -> Value {
    let name = bridge_name(function);
    let symbol = bridge_symbol(function);
    let (params, result) = match &function.kind {
        ExportKind::Function if function.abi == FunctionAbi::Scalar => {
            let mut params = function
                .parameters
                .iter()
                .map(|parameter| json!(abi_class(scalar_type(&parameter.ty))))
                .collect::<Vec<_>>();
            if !matches!(function.result, Type::Scalar(Scalar::Void)) {
                params.push(callback_entry(&[abi_class(scalar_type(&function.result))]));
            }
            (params, "i32")
        }
        ExportKind::Function => (vec![json!("string"), callback_entry(&["bytes"])], "i32"),
        ExportKind::Stream { .. } | ExportKind::Iterator { .. } => (
            vec![json!("string"), callback_entry(&["u32", "u32"])],
            "i32",
        ),
        ExportKind::Async { .. }
        | ExportKind::Callback { .. }
        | ExportKind::Object { .. }
        | ExportKind::Trait { .. } => unreachable!("unsupported export reached the manifest"),
    };
    json!({ "name": name, "symbol": symbol, "params": params, "returns": result })
}

fn system_libraries() -> Vec<&'static str> {
    if cfg!(target_os = "macos") {
        vec!["m"]
    } else {
        vec!["m", "dl", "pthread"]
    }
}

/// Render the TypeScript adapter that scriptc compiles into the executable.
pub(crate) fn render_adapter(functions: &[Function]) -> String {
    let mut output = String::from(
        "// Generated by cargo-eqts for the scriptc transport. Do not edit.\n\
         //\n\
         // These `declare function` declarations bind native symbols through\n\
         // `ffi.json` at link time. The module is scriptc-only: it has no\n\
         // runtime library loading and cannot run under Node, Bun, or Deno.\n\n",
    );
    output.push_str(&crate::type_definitions(functions));
    for function in functions {
        writeln!(output, "{}", adapter_declaration(function))
            .expect("writing to a string cannot fail");
    }
    output.push_str(
        "declare function eqtsScBridgePoll(hi: number, lo: number, emit: (data: Uint8Array) => void): number;\n\
         declare function eqtsScBridgeCancel(hi: number, lo: number): number;\n\
         declare function eqtsScBridgeDispose(hi: number, lo: number): number;\n\n",
    );
    output.push_str(ADAPTER_RUNTIME);
    for function in functions {
        writeln!(output, "{}", adapter_function(function))
            .expect("writing to a string cannot fail");
    }
    output
}

fn adapter_declaration(function: &Function) -> String {
    let name = bridge_name(function);
    match &function.kind {
        ExportKind::Function if function.abi == FunctionAbi::Scalar => {
            let mut parameters = function
                .parameters
                .iter()
                .map(|parameter| format!("{}: {}", parameter.name, ts_type(&parameter.ty)))
                .collect::<Vec<_>>();
            if !matches!(function.result, Type::Scalar(Scalar::Void)) {
                parameters.push(format!(
                    "emit: (value: {}) => void",
                    ts_type(&function.result)
                ));
            }
            format!(
                "declare function {name}({}): number;",
                parameters.join(", ")
            )
        }
        ExportKind::Function => format!(
            "declare function {name}(input: string, emit: (data: Uint8Array) => void): number;"
        ),
        ExportKind::Stream { .. } | ExportKind::Iterator { .. } => format!(
            "declare function {name}(input: string, emit: (hi: number, lo: number) => void): number;"
        ),
        ExportKind::Async { .. }
        | ExportKind::Callback { .. }
        | ExportKind::Object { .. }
        | ExportKind::Trait { .. } => unreachable!("unsupported export reached the adapter"),
    }
}

const ADAPTER_RUNTIME: &str = "export class EqtsError extends Error {\n\
\x20 readonly code: string;\n\
\x20 private readonly detail: string;\n\
\x20 constructor(code: string, value: string) {\n\
\x20   super(value.length > 0 ? value : `eqts error: ${code}`);\n\
\x20   this.name = \"EqtsError\";\n\
\x20   this.code = code;\n\
\x20   this.detail = value;\n\
\x20 }\n\
\x20 get value(): unknown { return this.detail; }\n\
}\n\n\
function __eqtsDecode(data: Uint8Array): string {\n\
\x20 return new TextDecoder().decode(data);\n\
}\n\n\
function checkStatus(status: number, name: string, detail: string = \"\"): void {\n\
\x20 if (status === 0) return;\n\
\x20 let code = \"ABI_ERROR\";\n\
\x20 if (status === 1) code = \"RUST_PANIC\";\n\
\x20 else if (status === 2) code = \"NULL_OUTPUT\";\n\
\x20 else if (status === 3) code = \"INVALID_INPUT\";\n\
\x20 else if (status === 4) code = \"ENCODE_FAILURE\";\n\
\x20 else if (status === 14) code = \"UNKNOWN_HANDLE\";\n\
\x20 throw new EqtsError(code, detail.length > 0 ? detail : `eqts call ${name} failed with ABI status ${status}`);\n\
}\n\n\
export class EqtsHandle<T> {\n\
\x20 private readonly hi: number;\n\
\x20 private readonly lo: number;\n\
\x20 private __eqtsDisposed: boolean = false;\n\
\x20 constructor(hi: number, lo: number) { this.hi = hi; this.lo = lo; }\n\
\x20 get disposed(): boolean { return this.__eqtsDisposed; }\n\
\x20 dispose(): void {\n\
\x20   if (this.__eqtsDisposed) return;\n\
\x20   this.__eqtsDisposed = true;\n\
\x20   eqtsScBridgeDispose(this.hi, this.lo);\n\
\x20 }\n\
\x20 async next(): Promise<IteratorResult<T>> {\n\
\x20   if (this.__eqtsDisposed) throw new EqtsError(\"USE_AFTER_DISPOSE\", \"reactive handle is disposed\");\n\
\x20   for (;;) {\n\
\x20     let __eqtsText = \"\";\n\
\x20     const __eqtsStatus = eqtsScBridgePoll(this.hi, this.lo, (data: Uint8Array) => { __eqtsText = __eqtsDecode(data); });\n\
\x20     if (__eqtsStatus === 14) throw new EqtsError(\"UNKNOWN_HANDLE\", __eqtsText);\n\
\x20     if (__eqtsStatus === 10) { await new Promise<void>((resolve) => { setTimeout(resolve, 0); }); continue; }\n\
\x20     if (__eqtsStatus === 11 || __eqtsStatus === 13) return { value: JSON.parse(__eqtsText) as T, done: false };\n\
\x20     if (__eqtsStatus === 12) { this.dispose(); return { value: undefined, done: true }; }\n\
\x20     throw new EqtsError(\"REACTIVE_POLL\", `reactive poll failed with ABI status ${__eqtsStatus}`);\n\
\x20   }\n\
\x20 }\n\
\x20 [Symbol.asyncIterator](): EqtsHandle<T> { return this; }\n\
}\n\n";

fn adapter_function(function: &Function) -> String {
    let name = typescript_name(&function.name);
    let bridge = bridge_name(function);
    match &function.kind {
        ExportKind::Function if function.abi == FunctionAbi::Scalar => {
            scalar_adapter(function, &name, &bridge)
        }
        ExportKind::Function => json_adapter(function, &name, &bridge),
        ExportKind::Stream { item } | ExportKind::Iterator { item } => {
            reactive_adapter(function, item, &name, &bridge)
        }
        ExportKind::Async { .. }
        | ExportKind::Callback { .. }
        | ExportKind::Object { .. }
        | ExportKind::Trait { .. } => unreachable!("unsupported export reached the adapter"),
    }
}

fn scalar_adapter(function: &Function, name: &str, bridge: &str) -> String {
    let parameters = function
        .parameters
        .iter()
        .map(|parameter| format!("{}: {}", parameter.name, ts_type(&parameter.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = function
        .parameters
        .iter()
        .map(|parameter| parameter.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    if matches!(function.result, Type::Scalar(Scalar::Void)) {
        return format!(
            "export function {name}({parameters}): void {{\n  const __eqtsStatus = {bridge}({arguments});\n  checkStatus(__eqtsStatus, \"{}\");\n}}\n",
            function.name
        );
    }
    let result = ts_type(&function.result);
    let initial = if matches!(function.result, Type::Scalar(Scalar::Bool)) {
        "false"
    } else {
        "0"
    };
    let separator = if arguments.is_empty() { "" } else { ", " };
    format!(
        "export function {name}({parameters}): {result} {{\n  let __eqtsValue: {result} = {initial};\n  const __eqtsStatus = {bridge}({arguments}{separator}(value: {result}) => {{ __eqtsValue = value; }});\n  checkStatus(__eqtsStatus, \"{}\");\n  return __eqtsValue;\n}}\n",
        function.name
    )
}

fn json_adapter(function: &Function, name: &str, bridge: &str) -> String {
    let parameters = function
        .parameters
        .iter()
        .map(|parameter| format!("{}: {}", parameter.name, ts_type(&parameter.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = function
        .parameters
        .iter()
        .map(|parameter| scriptc_wire_encode(&parameter.name, &parameter.ty))
        .collect::<Vec<_>>()
        .join(", ");
    let status = format!(
        "  let __eqtsText = \"\";\n  const __eqtsStatus = {bridge}(JSON.stringify([{arguments}]), (data: Uint8Array) => {{ __eqtsText = __eqtsDecode(data); }});\n  checkStatus(__eqtsStatus, \"{}\", __eqtsText);\n",
        function.name
    );
    if matches!(function.result, Type::Scalar(Scalar::Void)) {
        return format!("export function {name}({parameters}): void {{\n{status}}}\n");
    }
    let result = ts_type(&function.result);
    let decode = match &function.result {
        Type::Owned(OwnedType::Result { ok, error }) => {
            let ok_cast = scriptc_cast_type(ok);
            let error_cast = scriptc_cast_type(error);
            let error_value = if matches!(**error, Type::Owned(OwnedType::String)) {
                "__eqtsDecoded.error".to_string()
            } else {
                format!(
                    "JSON.stringify({})",
                    scriptc_wire_decode("__eqtsDecoded.error", error)
                )
            };
            format!(
                "  const __eqtsDecoded = JSON.parse(__eqtsText) as {{ ok: {ok_cast} }} | {{ error: {error_cast} }};\n  if (\"error\" in __eqtsDecoded) throw new EqtsError(\"RUST_ERROR\", {error_value});\n  return {};\n",
                scriptc_wire_decode("__eqtsDecoded.ok", ok)
            )
        }
        ty => format!(
            "  const __eqtsDecoded = JSON.parse(__eqtsText) as {};\n  return {};\n",
            scriptc_cast_type(ty),
            scriptc_wire_decode("__eqtsDecoded", ty)
        ),
    };
    format!("export function {name}({parameters}): {result} {{\n{status}{decode}}}\n")
}

fn reactive_adapter(function: &Function, item: &Type, name: &str, bridge: &str) -> String {
    let parameters = function
        .parameters
        .iter()
        .map(|parameter| format!("{}: {}", parameter.name, ts_type(&parameter.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = function
        .parameters
        .iter()
        .map(|parameter| scriptc_wire_encode(&parameter.name, &parameter.ty))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "export function {name}({parameters}): EqtsHandle<{}> {{\n  let __eqtsHi = 0;\n  let __eqtsLo = 0;\n  const __eqtsStatus = {bridge}(JSON.stringify([{arguments}]), (hi: number, lo: number) => {{ __eqtsHi = hi; __eqtsLo = lo; }});\n  checkStatus(__eqtsStatus, \"{}\");\n  return new EqtsHandle<{}>(__eqtsHi, __eqtsLo);\n}}\n",
        ts_type(item),
        function.name,
        ts_type(item)
    )
}

/// The type a checked cast validates against: the wire shape, which differs from
/// the declared TypeScript type wherever JSON carries bytes as arrays or 64-bit
/// integers as strings.
fn scriptc_cast_type(ty: &Type) -> String {
    match ty {
        Type::Scalar(Scalar::U64 | Scalar::I64) => "string".to_string(),
        Type::Owned(OwnedType::Bytes) => "number[]".to_string(),
        Type::Owned(OwnedType::Vec { value }) => {
            format!("Array<{}>", scriptc_cast_type(value))
        }
        Type::Owned(OwnedType::Option { value }) => {
            format!("{} | null", scriptc_cast_type(value))
        }
        Type::Owned(OwnedType::Record { fields, .. }) => {
            let fields = fields
                .iter()
                .map(|field| format!("{}: {}", field.name, scriptc_cast_type(&field.ty)))
                .collect::<Vec<_>>()
                .join("; ");
            format!("{{ {fields} }}")
        }
        Type::Scalar(_) | Type::Owned(OwnedType::String | OwnedType::Enum { .. }) => ts_type(ty),
        Type::Owned(OwnedType::Result { ok, .. }) => scriptc_cast_type(ok),
    }
}
